---
- name: homebrew update/upgrade
  homebrew:
    update_homebrew: true
    upgrade_all: yes
- name: homebrew install
  homebrew:
    name: "{{ packages }}"
  vars:
    packages:
    - nkf
    - mas
    - tnftp
    - rclone
    - node
- name: homebrew cask upgrade
  homebrew_cask:
    upgrade_all: true
- name: homebrew cask install
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
    - caffeine
    - 1password
    - docker
    - visual-studio-code
    - amazon-workspaces
    - iterm2
    - google-chrome
    - tripmode
    - adguard
    - osxfuse
    - java
    - adobe-creative-cloud
    - skype
- name: mas install
  script: "../scripts/mas.sh {{ item.id }}"
  with_items:
  - { id: '417375580', name: 'BetterSnapTool' }
  - { id: '539883307', name: 'LINE' }
  - { id: '803453959', name: 'Slack' }
  - { id: '405399194', name: 'Kindle' }
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc not in [0, 1]
