---
- name: homebrew update/upgrade
  homebrew:
    update_homebrew: true
    upgrade_all: yes
- name: homebrew install
  homebrew:
    name: "{{ packages }}"
  vars:
    packages:
    - nkf
    - mas
- name: homebrew cask install
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
    - alfred
    - caffeine
    - 1password
    - docker
    - visual-studio-code
    - amazon-workspaces
    - iterm2
    - google-chrome
    - tripmode
    - adguard
- name: mas install
  script: "../scripts/mas.sh {{ item.id }}"
  with_items:
  - { id: '417375580', name: 'BetterSnapTool' }
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc not in [0, 1]
