---
- name: install apt packages
  become: yes
  apt: zsh
- name: change user shell to zsh
  become: yes
  user: name={{ system.user }} shell=/bin/zsh
- name: clone zdharma/zplugin repo
  git: repo=git://github.com/zdharma/zplugin.git dest=~/.zplugin/bin
- name: copy .zshrc to home directory
  template: src=.zshrc.tpl dest=~/.zshrc force=yes
