---
- name: install apt packages
  become: yes
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
    - mosh
    - tree
    - nodejs
    - npm
    - libx11-6
    - libx11-xcb1
    - libxcomposite1
    - libxcursor1
