---
- name: mkdir npm global directory
  file: path=~/.npm/global/ state=directory
- name: sudo apt install npm
  become: yes
  apt:
    name: npm
- name: set prefix 
  command: npm config set prefix '~/.npm/global'
- name: npm install -g npm
  npm:
    name: npm
    global: yes
- name: npm install -g packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
  - gatsby-cli
