---
- name: copy .vimrc to home directory
  template: src=.vimrc.tpl dest=~/.vimrc force=yes
- name: mkdir vim-plug install directory
  file: path=~/.vim/autoload/ state=directory
- name: get vim-plug file
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim 
- name: install vim-plugin
  command: vim -c PlugInstall -c q -c q
