---
- name: mkdir config directory
  file: path=~/.config/rclone/ state=directory
- name: copy .config file to home directory
  template: src={{ item }}.tpl dest=~/.config/rclone/{{ item }}
  with_items:
  - rclone.conf
- name: mkdir gdrive directory
  file: path=~/home/ state=directory
- name: rclone mount home:/ ~/home
  shell: rclone mount home:/ ~/home &
- name: mkdir gdrive directory
  file: path=~/work/ state=directory
- name: rclone mount work:/ ~/work
  shell: rclone mount work:/ ~/work &
